{fix} = require '../lib/coffee2closure'

describe 'hooks', ->

  describe 'injectConstructorIfMissing', ->

  it 'should add a constructor annotation', ->
    source = """
      var __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

      goog.provide('app.Employee');

      goog.require('app.Person');

      app.Employee = (function(_super) {

        __extends(Employee, _super);

        /**
          @param {string} name
          @extends {app.Person}
        */


        function Employee(name) {
          Employee.__super__.constructor.call(this, name);
        }

        return Employee;

      })(app.Person);

    """

    fixedSource = """
      // Generated by github.com/steida/coffee2closure 0.0.14
      goog.provide('app.Employee');
      goog.require('app.Person');

      /**
        @param {string} name
        @extends {app.Person}
        @constructor
      */
      app.Employee = function(name) {
        app.Employee.superClass_.constructor.call(this, name);
      }
      goog.inherits(app.Employee, app.Person);
    """
    fix(source).should.equal fixedSource

  it 'should not add a constructor annotation', ->
    source = """
      var __hasProp = {}.hasOwnProperty,
        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

      goog.provide('app.Employee');

      goog.require('app.Person');

      app.Employee = (function(_super) {

        __extends(Employee, _super);

        /**
          @param {string} name
          @constructor
          @extends {app.Person}
        */


        function Employee(name) {
          Employee.__super__.constructor.call(this, name);
        }

        return Employee;

      })(app.Person);

    """

    fixedSource = """
      // Generated by github.com/steida/coffee2closure 0.0.14
      goog.provide('app.Employee');
      goog.require('app.Person');

      /**
        @param {string} name
        @constructor
        @extends {app.Person}
      */
      app.Employee = function(name) {
        app.Employee.superClass_.constructor.call(this, name);
      }
      goog.inherits(app.Employee, app.Person);
    """
    fix(source).should.equal fixedSource
